backend:
  name: github
  repo: juchan0426/kimproduction.github.io # 본인 저장소
  branch: main
  auth_scope: repo
  app_id: "Ov23lidBF8L0M0sizs7m" # 본인 GitHub OAuth Client ID
  auth_endpoint: "https://netlify-cms-auth-proxy.herokuapp.com/auth"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "게시물"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
