backend:
  name: github
  repo: juchan0426-boop/kimproduction.github.io
  branch: main
  auth_type: implicit
  base_url: https://api.github.com

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
